### Begin DialogBlocks generated body
################################################################################
# Makefile generated by DialogBlocks
#
# Available configurations:
# releasemac
# releaselinux
################################################################################

CONFIG=releasemac

# releasemac
ifeq ($(CONFIG),releasemac)
WXWIN=/usr/local/src/wxWidgets-2.8.12
TOOLCHAINNAME=macd
WXVERSION:=$(shell echo `$(WXWIN)/GCCBuildDebugMac/wx-config --version`)
CXX=g++
LINKER=g++
CC=gcc
RESCOMP=windres.exe
RCFILEOBJ=SuperMouser_rc.o
RCFILESRC=SuperMouser.rc
RESOURCEOBJECT=
OUTPUTPATH=GCCReleaseMac
OBJECTPATH=GCCReleaseMac
BUILDPATHS=$(OBJECTPATH)
PROGRAM=SuperMouser
LIBS=$(shell $(WXWIN)/GCCBuildDebugMac/wx-config --inplace --exec-prefix="$(WXWIN)/GCCBuildDebugMac" --libs std --cxxflags)
LINKERFLAGS=
WARNINGFLAGS=-Wall -Wno-write-strings
OPTFLAGS=-O0
DEBUGFLAGS=-ggdb
LIBPATH=
CPPINC:=$(shell $(WXWIN)/GCCBuildDebugMac/wx-config --inplace --cxxflags)
GCCFLAGS= -arch i386
LDFLAGS=$(LIBS) $(LIBPATH) $(LINKERFLAGS)
CPPFLAGS=$(CPPINC) $(GCCFLAGS) $(DEBUGFLAGS) $(OPTFLAGS) $(WARNINGFLAGS)
LIBDIRNAME=$(WXWIN)/GCCBuildDebugMac/lib
RESPATH=--include-dir "$(WXWIN)/include" --include-dir "$(WXWIN)/contrib/include" --include-dir "$(WXWIN)/GCCBuildDebugMac/lib/wx/include/mac-ansi-debug-static-2.8"
MACPACKAGEINFO=$(OUTPUTPATH)/$(PROGRAM).app/Contents/PkgInfo
INFOPLISTSOURCE=$(WXWIN)/src/mac/carbon/Info.plist.in
ICNSSOURCE=$(WXWIN)/src/mac/carbon/wxmac.icns
ICNSDEST=$(OUTPUTPATH)/$(PROGRAM).app/Contents/Resources/wxmac.icns

# releaselinux
else
WXWIN=/usr/local/src/wxWidgets-2.8.12
TOOLCHAINNAME=gtk2
WXVERSION:=$(shell echo `$(WXWIN)/GCCBuildReleaseGTK2/wx-config --version`)
CXX=g++
LINKER=g++
CC=gcc
RESCOMP=windres.exe
RCFILEOBJ=SuperMouser_rc.o
RCFILESRC=SuperMouser.rc
RESOURCEOBJECT=
OUTPUTPATH=GCCReleaseLinux
OBJECTPATH=GCCReleaseLinux
BUILDPATHS=$(OBJECTPATH)
PROGRAM=SuperMouser
LIBS=$(shell $(WXWIN)/GCCBuildReleaseGTK2/wx-config --inplace --exec-prefix="$(WXWIN)/GCCBuildReleaseGTK2" --libs std --cxxflags)
LINKERFLAGS=
WARNINGFLAGS=-Wall -Wno-write-strings
OPTFLAGS=-O2
DEBUGFLAGS=
LIBPATH=
CPPINC:=$(shell $(WXWIN)/GCCBuildReleaseGTK2/wx-config --inplace --cxxflags)
GCCFLAGS=
LDFLAGS=$(LIBS) $(LIBPATH) $(LINKERFLAGS)
CPPFLAGS=$(CPPINC) $(GCCFLAGS) $(DEBUGFLAGS) $(OPTFLAGS) $(WARNINGFLAGS)
LIBDIRNAME=$(WXWIN)/GCCBuildReleaseGTK2/lib
RESPATH=--include-dir "$(WXWIN)/include" --include-dir "$(WXWIN)/contrib/include" --include-dir "$(WXWIN)/GCCBuildReleaseGTK2/lib/wx/include/gtk2-ansi-release-static-2.8"
MACPACKAGEINFO=
endif

OBJECTS=$(OBJECTPATH)/abstractwindow.o $(OBJECTPATH)/supermouserapp.o $(RESOURCEOBJECT)

all:	$(BUILDPATHS) $(MACPACKAGEINFO) $(OUTPUTPATH)/$(PROGRAM)

$(OBJECTPATH):
	mkdir -p $(OBJECTPATH)

clean:
	rm -f $(OBJECTPATH)/*.o
	rm -f $(OBJECTPATH)/*.res
	rm -fr .deps .pch
	rm -fr $(PROGRAM).app
	rm -f $(OUTPUTPATH)/$(PROGRAM)

help:
	@echo "Usage: make -f Makefile CONFIG=[releasemac|releaselinux] [all|clean|help]"

$(OUTPUTPATH)/$(PROGRAM):	$(OBJECTS)
	$(LINKER) -o $@ $(OBJECTS) $(LDFLAGS)


# Windows only
$(OBJECTPATH)/$(RCFILEOBJ):	$(RCFILESRC)
	$(RESCOMP) --use-temp-file -i$< -o$@ $(RESPATH) --include-dir . --define NOPCH

# Mac only
$(OUTPUTPATH)/$(PROGRAM).app/Contents/PkgInfo: $(OUTPUTPATH)/$(PROGRAM) $(INFOPLISTSOURCE) $(ICNSSOURCE)
	mkdir -p $(OUTPUTPATH)/$(PROGRAM).app/Contents
	mkdir -p $(OUTPUTPATH)/$(PROGRAM).app/Contents/MacOS
	mkdir -p $(OUTPUTPATH)/$(PROGRAM).app/Contents/Resources
	sed -e "s/IDENTIFIER/$(PROGRAM)/" \
	-e "s/EXECUTABLE/$(PROGRAM)/" \
	-e "s/VERSION/$(WXVERSION)/" \
	$(INFOPLISTSOURCE) >$(OUTPUTPATH)/$(PROGRAM).app/Contents/Info.plist
	echo -n "APPL????" >$(OUTPUTPATH)/$(PROGRAM).app/Contents/PkgInfo
	ln -f $(OUTPUTPATH)/$(PROGRAM) $(OUTPUTPATH)/$(PROGRAM).app/Contents/MacOS/$(PROGRAM)
	cp -f $(ICNSSOURCE) $(ICNSDEST)

$(OBJECTPATH)/abstractwindow.o:	src/abstractwindow.cpp src/abstractwindow.h
	$(CXX) -c -o $@ $(CPPFLAGS) src/abstractwindow.cpp

$(OBJECTPATH)/supermouserapp.o:	src/supermouserapp.cpp src/supermouserapp.h src/abstractwindow.h
	$(CXX) -c -o $@ $(CPPFLAGS) src/supermouserapp.cpp

.PHONY:	all clean
### End DialogBlocks generated body
